/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts";

/*
 * Type representing codename of 'Default project language' language
 */
export type DefaultProjectLanguageLanguageCodename = keyof Pick<
  Record<LanguageCodenames, null>,
  "default"
>;

/*
 * Typeguard for codename of 'Default project language' language
 */
export function isDefaultProjectLanguageLanguageCodename(
  value: string | undefined | null,
): value is DefaultProjectLanguageLanguageCodename {
  return (
    typeof value === "string" &&
    value === ("default" satisfies DefaultProjectLanguageLanguageCodename)
  );
}
