/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

export * from "./collections/default-collection.generated.ts";
export * from "./languages/default-project-language-language.generated.ts";
export * from "./system/collections.generated.ts";
export * from "./system/elements.generated.ts";
export * from "./system/languages.generated.ts";
export * from "./system/main.system.generated.ts";
export * from "./system/snippets.generated.ts";
export * from "./system/taxonomies.generated.ts";
export * from "./system/types.generated.ts";
export * from "./system/workflows.generated.ts";
export * from "./taxonomies/event-topic.generated.ts";
export * from "./taxonomies/event-type.generated.ts";
export * from "./types/article.generated.ts";
export * from "./types/event.generated.ts";
export * from "./types/landing-page.generated.ts";
export * from "./types/solution.generated.ts";
export * from "./types/video.generated.ts";
export * from "./workflows/default-workflow.generated.ts";
