/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { TypeCodenames } from "../system/types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Solution' type
 */
export type SolutionTypeCodename = keyof Pick<Record<TypeCodenames, null>, "solution">;

/*
 * Typeguard for codename of 'Solution' type
 */
export function isSolutionTypeCodename(
  value: string | undefined | null,
): value is SolutionTypeCodename {
  return typeof value === "string" && value === ("solution" satisfies SolutionTypeCodename);
}

/*
 * Solution
 *
 * Id: 38f94bc7-66ee-5c66-8402-15eb237d9835
 * Codename: solution
 * External Id: solution
 */
export type SolutionType = IContentItem<
  {
    /*
     * Headline
     *
     * Codename: headline
     * Id: 9148131a-90f6-588a-bea4-c0397dbc554b
     * External Id: solution_default_headline_element
     * Type: text
     * Required: true
     */
    readonly headline: Elements.TextElement;

    /*
     * Introduction
     *
     * Codename: introduction
     * Id: ec1fba9b-f3ed-5653-ac01-9815dca28b61
     * External Id: solution_default_introduction_element
     * Type: text
     * Required: true
     */
    readonly introduction: Elements.TextElement;

    /*
     * Image
     *
     * Codename: image
     * Id: 481aa452-c113-5bb1-ae61-21b112bd0841
     * External Id: solution_default_image_element
     * Type: asset
     * Required: true
     */
    readonly image: Elements.AssetsElement;
  },
  SolutionTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Solution
 */
export type SolutionTypeElementCodenames = "headline" | "introduction" | "image";

/*
 * Type guard for Solution
 *
 * Id: 38f94bc7-66ee-5c66-8402-15eb237d9835
 * Codename: solution
 * External Id: solution
 */
export function isSolutionType(item: IContentItem | undefined | null): item is SolutionType {
  return item?.system.type === ("solution" satisfies SolutionTypeCodename);
}
