/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
  "headline",
  "introduction",
  "image",
  "name",
  "start_date",
  "end_date",
  "event_type",
  "event_topic",
  "description",
  "video_link",
  "caption",
  "autoplay",
  "subheadline",
  "hero_image",
  "body_copy",
  "featured_content",
  "title",
  "publish_date",
] as const;

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number];

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
  return typeof value === "string" && (elementCodenames as readonly string[]).includes(value);
}
