/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all language codenames
 */
export const languageCodenames = ["default"] as const;

/*
 * Type representing all language codenames
 */
export type LanguageCodenames = (typeof languageCodenames)[number];

/*
 * Typeguard for language codename
 */
export function isLanguageCodename(value: string | undefined | null): value is LanguageCodenames {
  return typeof value === "string" && (languageCodenames as readonly string[]).includes(value);
}
