/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

import type { IDeliveryClient } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "./collections.generated.ts";
import type { ElementCodenames } from "./elements.generated.ts";
import type { LanguageCodenames } from "./languages.generated.ts";
import type { TaxonomyCodenames } from "./taxonomies.generated.ts";
import type { CoreType, TypeCodenames } from "./types.generated.ts";
import type { WorkflowCodenames, WorkflowStepCodenames } from "./workflows.generated.ts";

/*
 * Core types for 'IDeliveryClient'
 */
export type CoreClientTypes = {
  readonly collectionCodenames: CollectionCodenames;
  readonly contentItemType: CoreType;
  readonly contentTypeCodenames: TypeCodenames;
  readonly elementCodenames: ElementCodenames;
  readonly languageCodenames: LanguageCodenames;
  readonly taxonomyCodenames: TaxonomyCodenames;
  readonly workflowCodenames: WorkflowCodenames;
  readonly workflowStepCodenames: WorkflowStepCodenames;
};

/*
 * Typed delivery client. Use this instead of 'IDeliveryClient'
 */
export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>;
