/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kickstart [Production Source Project]
 * Environment: Kickstart Sample Apps Complete
 * Id: 979bdb48-cb15-00cd-a705-d46c4aab2041
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts";

/*
 * Type representing codename of 'Default' collection
 */
export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">;

/*
 * Typeguard for codename of 'Default' collection
 */
export function isDefaultCollectionCodename(
  value: string | undefined | null,
): value is DefaultCollectionCodename {
  return typeof value === "string" && value === ("default" satisfies DefaultCollectionCodename);
}
